var searchData=
[
  ['serdesbytecopy_101',['SerdesByteCopy',['../structcheckpoint_1_1_serdes_byte_copy.html',1,'checkpoint']]],
  ['serializablebase_102',['SerializableBase',['../structcheckpoint_1_1dispatch_1_1vrt_1_1_serializable_base.html',1,'checkpoint::dispatch::vrt']]],
  ['serializablederived_103',['SerializableDerived',['../structcheckpoint_1_1dispatch_1_1vrt_1_1_serializable_derived.html',1,'checkpoint::dispatch::vrt']]],
  ['serializabletraits_104',['SerializableTraits',['../structcheckpoint_1_1_serializable_traits.html',1,'checkpoint']]],
  ['serialization_5ferror_105',['serialization_error',['../structcheckpoint_1_1dispatch_1_1serialization__error.html',1,'checkpoint::dispatch']]],
  ['serialize_5fconstruct_5ftag_106',['SERIALIZE_CONSTRUCT_TAG',['../structcheckpoint_1_1dispatch_1_1_s_e_r_i_a_l_i_z_e___c_o_n_s_t_r_u_c_t___t_a_g.html',1,'checkpoint::dispatch']]],
  ['serialize_5ft_107',['serialize_t',['../structcheckpoint_1_1_serializable_traits.html#a416ff19cd1038279ace5cb49e3a9fb7d',1,'checkpoint::SerializableTraits']]],
  ['serializedinfo_108',['SerializedInfo',['../structcheckpoint_1_1_serialized_info.html',1,'checkpoint']]],
  ['serializeentry_109',['SerializeEntry',['../structcheckpoint_1_1detail_1_1_serialize_entry.html',1,'checkpoint::detail']]],
  ['serializeentry_3c_20arg_2c_20args_2e_2e_2e_20_3e_110',['SerializeEntry&lt; Arg, Args... &gt;',['../structcheckpoint_1_1detail_1_1_serialize_entry_3_01_arg_00_01_args_8_8_8_01_4.html',1,'checkpoint::detail']]],
  ['serializeentry_3c_3e_111',['SerializeEntry&lt;&gt;',['../structcheckpoint_1_1detail_1_1_serialize_entry_3_4.html',1,'checkpoint::detail']]],
  ['serializer_5f_112',['serializer_',['../structcheckpoint_1_1dispatch_1_1vrt_1_1serializer__registry_1_1_serializer_entry.html#a964df1472ba3ce4732531609f448206d',1,'checkpoint::dispatch::vrt::serializer_registry::SerializerEntry']]],
  ['serializerdispatchbyte_113',['SerializerDispatchByte',['../structcheckpoint_1_1dispatch_1_1_serializer_dispatch_byte.html',1,'checkpoint::dispatch']]],
  ['serializerdispatchnonbyte_114',['SerializerDispatchNonByte',['../structcheckpoint_1_1dispatch_1_1_serializer_dispatch_non_byte.html',1,'checkpoint::dispatch']]],
  ['serializerentry_115',['SerializerEntry',['../structcheckpoint_1_1dispatch_1_1vrt_1_1serializer__registry_1_1_serializer_entry.html',1,'checkpoint::dispatch::vrt::serializer_registry']]],
  ['serializerref_116',['SerializerRef',['../structcheckpoint_1_1_serializer_ref.html',1,'checkpoint']]],
  ['serializertraits_117',['SerializerTraits',['../structcheckpoint_1_1_serializer_traits.html',1,'checkpoint']]],
  ['serializevirtualtypeifneeded_118',['SerializeVirtualTypeIfNeeded',['../structcheckpoint_1_1_serialize_virtual_type_if_needed.html',1,'checkpoint']]],
  ['setvirtualdisabled_119',['setVirtualDisabled',['../structcheckpoint_1_1_base_serializer.html#ab16e2ffa62f03f8410b116c637bd4adc',1,'checkpoint::BaseSerializer']]],
  ['size_5f_120',['size_',['../structcheckpoint_1_1dispatch_1_1vrt_1_1objregistry_1_1_object_entry.html#a4395eb53a4569f96fde3dcf4e9b2ad02',1,'checkpoint::dispatch::vrt::objregistry::ObjectEntry']]],
  ['sizer_121',['Sizer',['../structcheckpoint_1_1_sizer.html',1,'checkpoint::Sizer'],['../structcheckpoint_1_1_sizer.html#a17995329af9eec00859e86c6fabf4890',1,'checkpoint::Sizer::Sizer()']]],
  ['skip_122',['skip',['../structcheckpoint_1_1_base_serializer.html#a7e3575fbbd4bf5bc39d8efb67c014e07',1,'checkpoint::BaseSerializer']]],
  ['streampacker_123',['StreamPacker',['../structcheckpoint_1_1_stream_packer.html',1,'checkpoint']]],
  ['streamunpacker_124',['StreamUnpacker',['../structcheckpoint_1_1_stream_unpacker.html',1,'checkpoint']]]
];
